// src/utils/file.ts
import JSZip from 'jszip';

/**
 * Lead Architect Splitting Logic with CI/CD Integration
 * Parses AI output and generates a full Playwright repository structure.
 */
export const downloadProjectZip = async (content: string, template: 'pom' | 'step-defs') => {
  if (!content) return;

  const zip = new JSZip();
  const root = zip.folder("playwright-automation");

  // --- 1. Infrastructure: CI/CD Pipeline Generator (Goal #4) ---
  
  // GitHub Actions Workflow
  root?.file(".github/workflows/playwright.yml", `
name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  `.trim());

  // Professional package.json
  root?.file("package.json", JSON.stringify({
    name: "playwright-automation-project",
    version: "1.0.0",
    description: "Architect-level Playwright automation suite generated by ShipFast QA",
    devDependencies: {
      "@playwright/test": "^1.49.0",
      "@types/node": "^20.0.0",
      "typescript": "^5.0.0"
    },
    scripts: {
      "test": "npx playwright test",
      "test:headed": "npx playwright test --headed",
      "show-report": "npx playwright show-report"
    }
  }, null, 2));

  // Lead Architect Playwright Config
  root?.file("playwright.config.ts", `
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000', // Update this as needed
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit', use: { ...devices['Desktop Safari'] } },
  ],
});
  `.trim());

  // --- 2. Logic: Splitting & Categorization ---

  const fileMarkerRegex = /\/\/ File: ([\w\/\.-]+).*\n([\s\S]*?)(?=\/\/ File:|$)/g;
  const matches = [...content.matchAll(fileMarkerRegex)];

  if (matches.length > 0) {
    matches.forEach(match => {
      const filePath = match[1].trim();
      const fileContent = match[2].trim();
      root?.file(filePath, fileContent);
    });
  } else if (template === 'pom') {
    const pageClassRegex = /(class (\w+Page)[\s\S]*?^})/gm;
    let mainTestFile = content;
    const foundPages: { name: string; content: string }[] = [];

    let match;
    while ((match = pageClassRegex.exec(content)) !== null) {
      const className = match[2];
      const classCode = match[1];
      foundPages.push({ name: className, content: classCode });
      mainTestFile = mainTestFile.replace(classCode, "");
    }

    foundPages.forEach(p => {
      root?.file(`models/${p.name}.ts`, `import { Page, expect } from '@playwright/test';\n\nexport ${p.content}`);
    });

    const imports = foundPages.map(p => `import { ${p.name} } from '../models/${p.name}';`).join('\n');
    root?.file("tests/gherkin.spec.ts", `${imports}\n\n${mainTestFile.trim()}`);
  } else {
    root?.file("tests/steps.spec.ts", content);
  }

  // --- 3. Finalization: Trigger Download ---

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `playwright-architect-project.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};